### ISSUE TITLE
Move the UI to React using a front-end library

### ISSUE THREAD

**Issue by joeitu** [alexander34ro/DevOps#18]
**TODO:** Refactor old HTML and CSS code into the new react client

_Discussion: what framework should we be using?_
https://www.codeinwp.com/blog/react-ui-component-libraries-frameworks/

### Bulma
https://bulma.io/

### React Bootstrap
https://react-bootstrap.github.io/

### Semantic UI
https://semantic-ui.com/

### Material
https://material-ui.com

**Comment by alexander34ro** [comment]
@joeitu let's discuss what would be the best front-end library to use for our UI

**Comment by joeitu** [comment]
We'll be using using Semantic UI for the ease of use and the previous experiences of the team with the framework

**Comment by joeitu** [comment]
Semantic also has a build-in component for "feed" ( ~ social media post ) which simplify a lot of work

**Comment by joeitu** [comment]
**Bulma**

Bulma is a great CSS framework but the react librairy is pretty poor compare to Material and Semantic. 
The documentation is also not as rich as the other framework ( [https://react-bulma.dev/en/documentation/layout/level](url) ). It seems to be a guy side project and still work in project.

**Comment by geoox** [comment]
Why React is best suited for our project:

- Performance: 
React is one of the most performant front end technology available, the other choices being Angular or Vue. Several benchmarks have been performed by individuals and in most of them react came first when it came to performance and ease of use 
e.g. https://medium.com/@mustwin/is-react-fast-enough-bca6bef89a6

- Easy integration: 
Being a library and not a framework dedicated to the development of web applications, React can also be integrated into existing projects for the development of targeted parts. Its use is also independent of the technological stack of the project.

- Strong Community: 
React is a reliable and up-to-date technology, thanks to the community and solid corporate support (Facebook dev team)
