### ISSUE TITLE
[URGENT] API Query

### ISSUE THREAD

**Issue by jianupetrut** [alexander34ro/DevOps#37]
group l (Blanao) it seems as if you are returning an empty JSON object when I query `https://<your_api_domain>/latest`

**Comment by alexander34ro** [comment]
Requests to /latest should return the first trending video on YouTube.

Ca sa eficientizam, am putea sa cautam doar pe canalul Dani Mocanu dupa cel mai recent clip si sa filtram sa fie doar manelele care au in nume {anul_curent + 1}.

**Comment by alexander34ro** [comment]
Not repro

![Screenshot from 2020-02-29 16-33-45](https://user-images.githubusercontent.com/16760229/75610426-52cd9d80-5b11-11ea-824e-9521ca54e1cb.png)

**Comment by alexander34ro** [comment]
Repro

![Screenshot from 2020-02-29 16-38-13](https://user-images.githubusercontent.com/16760229/75610505-ef903b00-5b11-11ea-875f-20a4a80d09e1.png)

**Comment by alexander34ro** [comment]
![image](https://user-images.githubusercontent.com/16760229/75614760-575b7b80-5b3c-11ea-8630-0dfb2849aa8c.png)

`Latest: undefined`

**Comment by alexander34ro** [comment]
Added logs for latest in bf21d5c197a05301908bd604555c8740560d0cb7

Added guard against undefined latest in aa8fd7871bf018b3a59583bbaad29823fc764d9a
